[pytest]
pythonpath = .
filterwarnings =
    ignore:Converting `np.inexact` or `np.floating` to a dtype is deprecated:DeprecationWarning:shap.*
    ignore:The set_bad function will be deprecated:PendingDeprecationWarning:shap.*
    ignore:The set_over function will be deprecated:PendingDeprecationWarning:shap.*
    ignore:The set_under function will be deprecated:PendingDeprecationWarning:shap.*
